config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new', as: 'new_task'
  post 'tasks', to: 'tasks#create'
  get '/tasks/:id', to: 'tasks#show', as: 'task'
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id', to: 'tasks#update', as: 'update_task'
  delete 'tasks/:id', to: 'tasks#destroy', as: 'destroy_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new # Needed to instantiate the form_with
  end

  def create
    @task = Task.new(task_params)
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_with(model: @task, url: update_task_path(@task), method: :patch) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :details %>
    <%= form.text_area :details %>
  </div>

  <div>
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.submit "Update Task" %>
  </div>
<% end %>

<p>
  <%= link_to 'Back to Task Details', task_path(@task) %>
</p>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <!-- <%= task.title %> -->
      <%= link_to task.title, task_path(task) %>
      <!-- - <%= task.details %> -->
      <!-- <%= link_to 'Edit', edit_task_path(task) %> |
      <%= link_to 'Delete', destroy_task_path(task), method: :delete, data: { confirm: 'Are you sure you want to delete this task?' } %> -->
    </li>
  <% end %>
</ul>

<p>
  <%= link_to 'Add a new task', new_task_path %>
</p>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with(model: @task, url: tasks_path, method: :post) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :details %>
    <%= form.text_area :details %>
  </div>

  <div>
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.submit "Create Task" %>
  </div>
<% end %>

<p>
  <%= link_to 'Back to Task List', tasks_path %>
</p>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p>
  <%= @task.details %>
</p>

<div>
<%= link_to "Back to Tasks List", tasks_path %>
</div>

<div>
  <p><%= link_to 'Edit Task', edit_task_path(@task) %></p>
  </div>

<div>
<%= link_to "Delete",
task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
</div>